# Generated by Django 5.1 on 2024-09-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_customer_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='timezone',
            field=models.CharField(choices=[('Europe/Budapest', 'Budapest (Hungary)'), ('Europe/London', 'London'), ('Europe/Paris', 'Paris')], default='Europe/Budapest', max_length=50),
        ),
    ]
