# Generated by Django 5.1 on 2024-09-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('org_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('voice', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('first_message', models.TextField(blank=True, null=True)),
                ('voicemail_message', models.TextField(blank=True, null=True)),
                ('end_call_message', models.TextField(blank=True, null=True)),
                ('transcriber', models.CharField(blank=True, max_length=255, null=True)),
                ('client_messages', models.JSONField(blank=True, null=True)),
                ('server_messages', models.JSONField(blank=True, null=True)),
                ('end_call_phrases', models.JSONField(blank=True, null=True)),
                ('num_words_to_interrupt_assistant', models.IntegerField(blank=True, null=True)),
                ('background_sound', models.CharField(blank=True, max_length=255, null=True)),
                ('is_server_url_secret_set', models.BooleanField(default=False)),
            ],
        ),
    ]
