# Generated by Django 5.1 on 2024-09-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
