# Generated by Django 5.1 on 2024-09-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_assistant_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
