# Generated by Django 5.1 on 2024-09-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_assistant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL-friendly identifier automatically generated from the id', max_length=255, null=True, unique=True),
        ),
    ]
