# Generated by Django 5.1 on 2024-09-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_assistant_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='assistant',
            name='analysis_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='artifact_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='backchanneling_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistant',
            name='background_denoising_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistant',
            name='credential_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='first_message_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='hipaa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistant',
            name='max_duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='message_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='model_output_in_messages_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistant',
            name='server_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='server_url_secret',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='silence_timeout_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='start_speaking_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='stop_speaking_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='transport_configurations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistant',
            name='voicemail_detection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='model',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='transcriber',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='voice',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['name'], name='management__name_637ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='assistant',
            index=models.Index(fields=['created_at'], name='management__created_27909f_idx'),
        ),
    ]
