# Generated by Django 5.1 on 2024-09-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_assistant_options_assistant_analysis_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('org_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('voice', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('model', models.JSONField()),
                ('recording_enabled', models.BooleanField(default=True)),
                ('first_message', models.TextField()),
                ('transcriber', models.JSONField()),
                ('silence_timeout_seconds', models.IntegerField()),
                ('client_messages', models.JSONField()),
                ('server_messages', models.JSONField()),
                ('end_call_phrases', models.JSONField()),
                ('hipaa_enabled', models.BooleanField(default=False)),
                ('max_duration_seconds', models.IntegerField()),
                ('background_sound', models.CharField(max_length=255)),
                ('backchanneling_enabled', models.BooleanField(default=False)),
                ('first_message_mode', models.CharField(max_length=255)),
                ('voicemail_detection', models.JSONField()),
                ('background_denoising_enabled', models.BooleanField(default=False)),
                ('model_output_in_messages_enabled', models.BooleanField(default=False)),
                ('is_server_url_secret_set', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Assistant',
        ),
    ]
