# Generated by Django 5.1 on 2024-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_assistantmodel_delete_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmodel',
            name='end_call_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistantmodel',
            name='num_words_to_interrupt_assistant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assistantmodel',
            name='voicemail_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
